name: Manual Github Data Extract Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python dataExtract.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
          JIRA_INSTANCE: ${{ secrets.JIRA_INSTANCE }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          ARTIFACTORY_USERNAME: ${{ vars.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_USER: ${{ vars.ARTIFACTORY_USERNAME }} 
          ARTIFACTORY_API_TOKEN: ${{ secrets.ARTIFACTORY_API_TOKEN }}  
          ARTIFACTORY_FOLDER: 'CI'
          ARTIFACTORY_STAGE: ${{ github.head_ref || github.ref_name }}

      - name: Display Pull Request Titles
        run: cat list.log
